version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1430:1430"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    volumes:
      - ./resources/scripts/schemas.sql:/tmp/resources/scripts/schemas.sql
      - ./resources/scripts/init-schemas.sh:/tmp/resources/scripts/init-schemas.sh
    command: /bin/bash ./tmp/resources/scripts/init-schemas.sh
  app:
    image: jfdmagalhaes/blognews-fiap:latest
    depends_on:
      - db
    environment:
      - ConnectionStrings:DefaultConnection=Server=db,1430;Database=db_noticiastest;User=sa;Password=Pass@word;TrustServerCertificate=True;Pooling=false