apiVersion: v1
kind: Service
metadata:
  name: sql-service
  labels:
    app: sql-server
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30432
      name: "tcpsql"