apiVersion: v1
kind: Service
metadata:
  name: blognews-api
  labels:
    app: blognews-api
spec:
  type: ClusterIP
  ports:
  - port: 8999
    protocol: TCP
    targetPort: 8999
  selector:
    app: blognews-api