apiVersion: v1
kind: Service
metadata:
  name: blognews-service
  labels:
    run: blognews-service
spec:
  selector:
    app: blognews-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP