apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pv-claim
  labels:
    app: sql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi #1 GB
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script-configmap
data:
  init.sql: |-
    create database db_noticias;
    GO

    IF OBJECT_ID(N'dbo.Noticias') IS NOT NULL  
       DROP TABLE [dbo].Noticias;  
    GO

    use db_noticias
    CREATE TABLE Noticias (
        Id INT PRIMARY KEY IDENTITY,
        Titulo NVARCHAR(255) NOT NULL,
        Conteudo NVARCHAR(MAX) NOT NULL,
        DataPublicacao DATETIME NOT NULL,
        Autor NVARCHAR(255) NOT NULL
    );

    GO