apiVersion: v1
kind: Service
metadata:
  name: blognews-service
  labels:
    run: blognews-service
spec:
  selector:
    app: pod-blognews
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  type: LoadBalancer