name: Build and Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  applicationUnitTests: '$(System.DefaultWorkingDirectory)/Application.UnitTests/Application.UnitTests.csproj'
  infrastructureUnitTests: '$(System.DefaultWorkingDirectory)/Infrastructure.UnitTests/Infrastructure.UnitTests.csproj'
  integrationTests: '$(System.DefaultWorkingDirectory)/Infrastructure.IntegrationTests/Infrastructure.IntegrationTests.csproj'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Unit Test
      run: dotnet test $(applicationUnitTests) --no-build --verbosity normal
      
    - name: Integration Test
      run: |
        # TODO adicionar aqui os comandos para testes unitários.
